# Generated by Django 2.0.6 on 2018-06-13 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180612_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='due date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
