# Generated by Django 2.0.6 on 2018-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20180615_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
    ]
